### ISSUE TITLE
Dropdown menu broken

### ISSUE THREAD

**Issue by joshzzheng** [watson-developer-cloud/language-translator-nodejs#10]
For the demo on http://language-translation-demo.mybluemix.net/ 

The dropdown menu for Choose Language in the "Output" section is broken.

**Comment by germanattanasio** [comment]
you need to type a message to enable the dropdown in the output section

**Comment by joshzzheng** [comment]
I see.  I'm not sure if this is intuitive since people decide the input and output language before inputting text but my issue has been resolved.  Thanks!

**Comment by jsstylos** [comment]
I think that this is a legitimate usability bug. I ran into this also and it took me a minute to figure it out.
