### ISSUE TITLE
Arabic translation is completely off

### ISSUE THREAD

**Issue by MohammedFadin** [watson-developer-cloud/language-translator-nodejs#29]
Hello

Thanks for all the efforts. I noticed that the Arabic translation support is completely off. Sometimes the translations are totally irrelevant. To whom should we address this concern?

**Comment by nfriedly** [comment]
Hi @MohammedFadin,

Thanks for reporting this, I'll alert the right folks. Can you post a few examples here of what the source text is, what the incorrect translation is, and perhaps what a better translation might be (you can skip that last part if it's too much effort).

**Comment by nfriedly** [comment]
One more question, were you using the Conversational (`ar-en-conversational`) or the News (`ar-en`) domain?

**Comment by germanattanasio** [comment]
close due to inactivity
