### ISSUE TITLE
NMT model is not be used

### ISSUE THREAD

**Issue by makaishi2** [watson-developer-cloud/language-translator-nodejs#47]
This modification is not valid, I think.
There are two reson for it.

This modification is for client side code(browser code), but LT API call is issued at server side, then app.js (server side) should be modified, not demo.js .

I inspected Node.js library to access IBM Watson services, and knew that this code cannot handle special request haeder options.

So I modified app.js to invoke API directly, which seem to run good.
My code can be downloaded is follow:

https://github.com/makaishi2/language-translator-preview/blob/master/app.js

**Comment by germanattanasio** [comment]
@makaishi2 I have no idea what you are talking about. Are you saying that this demo has code that won't work?
If you add more information I may be able to help you here.

**Comment by makaishi2** [comment]
> Are you saying that this demo has code that won't work?

Yes. This modification has no effect to CALL MNT model.
The code your team modified was client side code.

```demo.js
      var restAPICall = {
        type: 'POST',
        url: '/api/translate',
        data: callData,
        dataType: 'json',
        headers: {
          'X-WDC-PL-OPT-OUT': $('input:radio[name=serRadio]:radio:checked').val(),
          'X-Watson-Technology-Preview': nmtValue
        },
        async: true
      };
```

Destination of this request is a server side node.js not Watson API.
Node.js resend this request to Watson API on a following code in app.js.

``` app.js
  app.post('/api/translate',  function(req, res, next) {
    console.log('/v2/translate');
    var params = extend({ 'X-WDC-PL-OPT-OUT': req.header('X-WDC-PL-OPT-OUT')}, req.body);
    translator.translate(params, function(err, models) {
     if (err)
       return next(err);
      else
        res.json(models);
     });
   });
```

This request has no special request header, then modification of demo.js has no effect.

I investigated Watson API node.js library which is used in app.js node.
I concluded that Watson API node.js library has no function to send request" true" Watson API with special request haeder.
 Then I modified app.js not to use Watson API node.js library.

Can you understand this?

**Comment by germanattanasio** [comment]
The Node SDK allows you to specify default headers. You just need to specify that header when creating the object.

```js
const myInstance = new watson.LanguageTranslatorV2({
  /* username, password, version, etc... */
  headers: {
    'X-Watson-Technology-Preview': true
  }
});
```

**Comment by makaishi2** [comment]
I tried following code, but preview option does not work well.

```app.js
var LanguageTranslatorV2 = require('watson-developer-cloud/language-translator/v2');

var translator = new LanguageTranslatorV2({
  headers: {
    'X-Watson-Technology-Preview': true
  },
  url: 'https://gateway.watsonplatform.net/language-translator/api'
 });
```

```app.js
app.post('/api/translate',  function(req, res, next) {
    console.log('/v2/translate');
    var params = extend({ 'X-WDC-PL-OPT-OUT': req.header('X-WDC-PL-OPT-OUT')}, req.body);
    translator.translate(params, function(err, models) {
    if (err)
        return next(err);
    else
        res.json(models);
    });
 })
```

I attached evidence.

Good case is a result of my modified code (call API direct not to use Watson library).
Bad case is a result of your advised modification.

Good case (direct API call)
![good-case](https://user-images.githubusercontent.com/25073940/35430484-ced08498-02bb-11e8-8dc9-d6793bbd6d90.png)

Bad case (using Watson library)
![bad-case](https://user-images.githubusercontent.com/25073940/35430491-d62ae27e-02bb-11e8-9fd3-d57104575752.png)

**Comment by germanattanasio** [comment]
You are adding the parameter to the `translate()` method not the constuctor.
Look at the code snippet I shared above.

**Comment by germanattanasio** [comment]
Here is where you need to add the header https://github.com/watson-developer-cloud/language-translator-nodejs/blob/master/app.js#L32

**Comment by germanattanasio** [comment]
I just tried and it worked so I'm going to close this issue for now. Feel free to reopen but I think it's a problem on your code not this demo or the SDK

**Comment by makaishi2** [comment]
In previous code, I already modified my constructor as follow.

```node.js
var LanguageTranslatorV2 = require('watson-developer-cloud/language-translator/v2');

var translator = new LanguageTranslatorV2({
     headers: {
       'X-Watson-Technology-Preview': true
     },
      url: 'https://gateway.watsonplatform.net/language-translator/api'
 });
```

And I added following debug code in watson API library (requestwrapper.js).
It seems no request header on API Call.

```requestwrapper.js
  // Path params
  options.url = parsePath(options.url, path);
  delete options.path;

  // Headers
  options.headers = extend({}, options.headers);

  if (!isBrowser) {
    options.headers['User-Agent'] = pkg.name + '-nodejs-' + pkg.version;
  }
  // debug code by akaishi
  console.log('headers');
  console.log(options.headers);

  // Query params
  if (options.qs && Object.keys(options.qs).length > 0) {
    options.useQuerystring = true;
  }

  // Add service default endpoint if options.url start with /
  if (options.url.charAt(0) === '/') {
    options.url = parameters.defaultOptions.url + options.url;
  }

  // Compression support
  options.gzip = true;

  return request(options, formatErrorIfExists(callback));
}
```

```
headers
{ Authorization: 'Basic OTE5YTUzODAtY2NmNC00ODY0LTkxMDAtY2RjZTUxZDY5ZTJlOlFpR282MFNqOEJwbw==',
  'User-Agent': 'watson-developer-cloud-nodejs-2.39.0' }
```

**Comment by germanattanasio** [comment]
@makaishi2 I've updated the code in this app. Can you try again with the proper constructor?
I updated the node sdk from 2.39.0 to 3.0.6
