### ISSUE TITLE
POST to language translator service for identify is sending key value pair in body

### ISSUE THREAD

**Issue by lbandera-ibm-research** [watson-developer-cloud/language-translator-nodejs#53]
The body of the POST to v2/identify should only contain the text input by the user. On the language translator front end log,  I am seeing the request as follows :+1: 
```{"text":"hello"}```
I should only see "hello" not a key / value pair. 
Can someone verify what is being sent to the language translator service for identify? If  a key / value pair is being sent for identify, change the code to only send the value.

**Comment by germanattanasio** [comment]
@lbandera-ibm-research the service supports `text/plain` where we will send only `hello`  or `application/json` (this case) where we send the text to translate as `{"text":"hello"}`

**Comment by germanattanasio** [comment]
Do you think the application is using `text/plain` and sending the json object described above?

**Comment by lbandera-ibm-research** [comment]
@germanattanasio  - The content type is 'text/plain' . It is  possible that the request is  sending an object as a text string.

**Comment by germanattanasio** [comment]
I think you are right @lbandera-ibm-research. Can you write a PR to fix this? Otherwise I can look at it next week

**Comment by lbandera-ibm-research** [comment]
I don't know how I would test any change or if I have permission in the repo. The body is set here:
https://github.com/watson-developer-cloud/node-sdk/blob/master/language-translator/v2-generated.ts#L123
``` 
  const body = _params.text;
    const parameters = {
      options: {
        url: '/v2/identify',
        method: 'POST',
        json: false,
        body,
      },
      defaultOptions: extend(true, {}, this._options, {
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'text/plain',
        }
      })
    };
```
If you tell me how I can test locally, I can try to change the code to fix it

**Comment by germanattanasio** [comment]
The README has everything you need to get started. You only need to have Node.js installed and credentials for Language Translator.
